import 'package:get/get.dart';

import 'localization_keys.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          LocalizationKeys.email: 'Email',
          LocalizationKeys.enter_phone_number: 'Enter your phone number',
          LocalizationKeys.phone_confirmation:
              'you will receive a confirmation code on your phone',
          LocalizationKeys.phone_number: 'Phone number',
          LocalizationKeys.phone_number_hint: '01xxxxxxxxx',
          LocalizationKeys.phone_number_error: 'Phone number is wrong',
          LocalizationKeys.phone_number_error_empty: 'Phone number is empty',
          LocalizationKeys.phone_number_error_length:
              'Phone number must be at least 11 digits',
          LocalizationKeys.phone_number_error_format:
              'Phone number must be in the format 01xxxxxxxxx',
          LocalizationKeys.app_login: 'Login with phone number',
          LocalizationKeys.app_logout: 'Logout',
          LocalizationKeys.app_logout_error: 'Logout error happened !',
          LocalizationKeys.login_google: 'Login with Google',
          LocalizationKeys.login_facebook: 'Login with Facebook',
          LocalizationKeys.or: 'OR',
          LocalizationKeys.filter: 'Filter',
          LocalizationKeys.filter_apply: 'Apply',
          LocalizationKeys.filter_clear_all: 'Clear all',
          LocalizationKeys.login_error: 'Login error happened !',
          LocalizationKeys.network_error: 'Network error happened !',
          LocalizationKeys.network_error_message:
              'Please check your internet connection and try again',
          LocalizationKeys.network_success: 'Network success !',
          LocalizationKeys.network_success_message:
              'You are connected to the internet',
          LocalizationKeys.facebook_login_error:
              'Login with Facebook error happened !',
          LocalizationKeys.government_cairo: 'Cairo',
          LocalizationKeys.area_saft: 'Saft',
          LocalizationKeys.area_dokki: 'Dokki',
          LocalizationKeys.choose_government: 'Choose government',
          LocalizationKeys.choose_area: 'Choose area',
          LocalizationKeys.choose_sex: 'Choose type',
          LocalizationKeys.choose_education: 'Choose Education',
          LocalizationKeys.choose_class: 'Choose Class',
          LocalizationKeys.choose_material: 'Choose Material',
          LocalizationKeys.male: 'Male',
          LocalizationKeys.female: 'Female',
          LocalizationKeys.education_secondary: 'Secondary',
          LocalizationKeys.education_prep: 'Prep',
          LocalizationKeys.secondary: 'Secondary',
          LocalizationKeys.prep: 'Prep',
          LocalizationKeys.class_level: 'class level',
          LocalizationKeys.secondary_class_level_one: 'First grade secondary',
          LocalizationKeys.secondary_class_level_two: 'Second grade secondary',
          LocalizationKeys.secondary_class_level_three: 'Third grade secondary',
          LocalizationKeys.prep_class_level_one: 'First grade prep',
          LocalizationKeys.prep_class_level_two: 'Second grade prep',
          LocalizationKeys.prep_class_level_three: 'Third grade prep',
          LocalizationKeys.home: 'Home',
          LocalizationKeys.follows: 'Follows',
          LocalizationKeys.follows2: 'Follows',
          LocalizationKeys.followers: 'Followers',
          LocalizationKeys.follow_teacher_no_posts:
              'You have to follow this teacher to see his news',
          LocalizationKeys.notifications: 'Notifications',
          LocalizationKeys.news: 'News',
          LocalizationKeys.news_teachers: 'Teachers news',
          LocalizationKeys.profile: 'Profile',
          LocalizationKeys.personal_info: 'Personal Info',
          LocalizationKeys.price_avg: 'Avg Price',
          //material
          LocalizationKeys.arabic: 'Arabic',
          LocalizationKeys.english: 'English',
          LocalizationKeys.math: 'Math',
          LocalizationKeys.science: 'Science',
          LocalizationKeys.french: 'French',
          LocalizationKeys.history: 'History',
          LocalizationKeys.geography: 'Geography',
          LocalizationKeys.biology: 'Biology',
          LocalizationKeys.chemistry: 'Chemistry',
          LocalizationKeys.physics: 'Physics',
          LocalizationKeys.german: 'German',
          LocalizationKeys.spanish: 'Spanish',
          LocalizationKeys.social: 'Social',
          LocalizationKeys.save: 'save',
          LocalizationKeys.rating: 'Rating',
          LocalizationKeys.rate_teacher: 'Rate Teacher',
          LocalizationKeys.add_review: 'Review Now',
          LocalizationKeys.review_added: 'Review Added',
          LocalizationKeys.reviews: 'Reviews',
          LocalizationKeys.no_reviews: 'No Reviews Yet',
          LocalizationKeys.review_text_hint: 'Write your review (optional)',
          LocalizationKeys.review_already_rated_teacher:
              'You already rated this teahcer',
          LocalizationKeys.lectures: 'Lectures',
          LocalizationKeys.app_student: 'Student App',
          LocalizationKeys.sms_code: 'SMS Code',
          LocalizationKeys.enter_six_digits_code: 'Enter 6 digits code',
          LocalizationKeys.enter_sms_code: 'Enter the code sent to you by SMS',
          LocalizationKeys.resend_sms_code: 'Resend SMS Code',
          LocalizationKeys.sms_code_not_sent_question: 'SMS Code not sent ?',
          LocalizationKeys.app_cancel: 'Cancel',
          LocalizationKeys.app_ok: 'Ok',
          LocalizationKeys.app_delete: 'Delete',
          LocalizationKeys.app_yes: 'Yes',
          LocalizationKeys.app_no: 'No',
          LocalizationKeys.logout_confirmation:
              'Are you sure you want to logout ?',
          LocalizationKeys.price_average: 'Average Price',
          LocalizationKeys.settings: 'Settings',
          LocalizationKeys.bookings: 'Bookings',
          LocalizationKeys.last_bookings: 'Last Bookings',
          LocalizationKeys.booking: 'Booking',
          LocalizationKeys.confirm_booking: 'confirm booking',
          LocalizationKeys.cancel_booking: 'cancel booking',
          LocalizationKeys.delete_follow: 'Cancel follow',
          LocalizationKeys.lecture_booked:
              'Lecture Booked! you can now go to your bookings to see the details',
          LocalizationKeys.follow_delete_question:
              'Are you sure you want to unfollow this teacher?',
          LocalizationKeys.booking_delete_question:
              'Are you sure you want to cancel this booking?',

          LocalizationKeys.profile_updated_error: 'Profile Updated Error',
          LocalizationKeys.profile_updated_successfully:
              'Profile Updated Successfully',
          LocalizationKeys.profile_image_updated_successfully:
              'Profile Image Updated Successfully',
          LocalizationKeys.profile_image_updated_error:
              'Profile Image Updated Error',
          LocalizationKeys.gallery: 'choose from gallery',
          LocalizationKeys.camera: 'take a photo',
          LocalizationKeys.confirm: 'Confirm',

          LocalizationKeys.email_error_empty: 'Email is empty',
          LocalizationKeys.email_error_format: 'Email in wrong format',
          LocalizationKeys.name_error_empty: 'Name is empty',
          LocalizationKeys.full_name: 'Full Name',
          LocalizationKeys.app_error_update_data: 'Error updating data',
          LocalizationKeys.choose_government_error:
              'you must choose government',
          LocalizationKeys.choose_area_error: 'you must choose area',
          LocalizationKeys.following: 'follow',
          LocalizationKeys.notifications_not_found: 'No Notifications Yet',
          LocalizationKeys.loading: 'Loading...',
          LocalizationKeys.lecture_already_booked:
              'you already booked this lecture',
          LocalizationKeys.lectures_not_found: 'No Lectures Found',
          LocalizationKeys.teachers_not_found: 'No Teachers Found',
          LocalizationKeys.bookings_not_found: 'bookings_not_found',
          LocalizationKeys.price_from: 'Price From',
          LocalizationKeys.price_to: 'Price To',
          LocalizationKeys.noFollows: 'You  have no Teachers to follow yet',

          //cairo area
          LocalizationKeys.cairo_nasrCity: 'Nasr City',
          LocalizationKeys.cairo_masr_gedida: 'Masr Gedida',
          LocalizationKeys.cairo_maady: 'Maady',
          LocalizationKeys.cairo_sayeda_zynab: 'Sayeda Zynab',
          LocalizationKeys.cairo_al_mokattam: 'Al Mokattam',
          LocalizationKeys.cairo_ain_shams: 'Ain Shams',
          LocalizationKeys.cairo_masra: 'Masra',
          LocalizationKeys.cairo_al_salam: 'Al Salam',
          LocalizationKeys.cairo_al_marg: 'Al Marg',
          LocalizationKeys.cairo_7lwan: '7lwan',
          LocalizationKeys.cairo_mataria: 'Mataria',
          LocalizationKeys.cairo_nozha: 'Nozha',
          LocalizationKeys.cairo_west_balad: 'West Balad',
          LocalizationKeys.cairo_azbkya: 'Azbkya',
          LocalizationKeys.cairo_moskey: 'Moskey',
          LocalizationKeys.cairo_waily: 'Waily',
          LocalizationKeys.cairo_bab_sh3rya: 'Bab Sh3rya',
          LocalizationKeys.cairo_bola2: 'Bola2',
          LocalizationKeys.cairo_eltben: 'Eltben',
          LocalizationKeys.cairo_3abden: '3abden',
          LocalizationKeys.cairo_3arb: '3\'arb',
          LocalizationKeys.cairo_monsh2t_nasr: 'Monsh2t Nasr',
          LocalizationKeys.cairo_mayo_15: 'May 15th',
          LocalizationKeys.cairo_al_basaten: 'Al Basaten',
          LocalizationKeys.cairo_al_5alefa: 'Al 5alefa',
          LocalizationKeys.cairo_dar_salam: 'Dar AlSalam',
          LocalizationKeys.cairo_torra: 'Torra',
          LocalizationKeys.cairo_misr_2adema: 'Misr 2adema',
          LocalizationKeys.cairo_amiria: 'Amiria',
          LocalizationKeys.cairo_zawya: 'Zawya',
          LocalizationKeys.cairo_zyton: 'Zyton',
          LocalizationKeys.cairo_sahel: 'Sahel',
          LocalizationKeys.cairo_sharabya: 'Sharabya',
          LocalizationKeys.cairo_7dayk_2obba: '7dayk 2obba',
          LocalizationKeys.cairo_rod_elfarag: 'Rod Elfarag',
          LocalizationKeys.cairo_shobra: 'Shobra',
          LocalizationKeys.cairo_7dayk_maady: '7dayk Maady',
          LocalizationKeys.cairo_tagamo3: '5th settlement',
          LocalizationKeys.cairo_zamalek: 'Zamalek',

          //giza area
          LocalizationKeys.giza_dokki_or_mohandessen: 'Dokki or Mohandessen',
          LocalizationKeys.giza_agoza: 'Agoza',
          LocalizationKeys.giza_kitkat: 'Kitkat',
          LocalizationKeys.giza_embaba: 'Embaba',
          LocalizationKeys.giza_warrak: 'Warrak',
          LocalizationKeys.giza_7dayk_ahram: '7dayk Ahram',
          LocalizationKeys.giza_3yad: '3yaT',
          LocalizationKeys.giza_kedasa: 'Kedasa',
          LocalizationKeys.giza_awsym: 'Awsym',
          LocalizationKeys.giza_mansorya: 'Mansorya',
          LocalizationKeys.giza_nahya: 'Nahya',
          LocalizationKeys.giza_saft: 'Saft',
          LocalizationKeys.giza_monsh2t_elbakary: 'Monsh2t Elbakary',
          LocalizationKeys.giza_she5_zayed: 'She5 Zayed',
          LocalizationKeys.giza_bolak_dakror: 'Bolak Dakror',
          LocalizationKeys.giza_midan_lebnan: 'Midan Lebnan',
          LocalizationKeys.giza_met_3o2ba: 'Met 3o2ba',
          LocalizationKeys.giza_medan_gam3a: 'Gam3a Square',
          LocalizationKeys.giza_midan_giza: 'Giza Square',
          LocalizationKeys.giza_haram: 'Haram',
          LocalizationKeys.giza_faisel: 'Faisel',
          LocalizationKeys.giza_omranya: 'Omranya',
          LocalizationKeys.giza_om_masryyn: 'Om Masryyn',
          LocalizationKeys.giza_m2mon: 'M2mon',
          LocalizationKeys.giza_6_october: '6 October',
          LocalizationKeys.giza_sa2ya_mky: 'Sa2ya Mky',
          LocalizationKeys.giza_monyb: 'Monyb',
          LocalizationKeys.giza_tersa: 'Tersa',
          LocalizationKeys.giza_hawamdya: 'Hawamdya',
          LocalizationKeys.giza_3zyzya: '3zyzya',
          LocalizationKeys.giza_s2ara: 'S2ara',
          LocalizationKeys.giza_bdrshen: 'Bdrshen',
        },
        'ar_EG': {
          LocalizationKeys.email: 'البريد الإلكتروني',
          LocalizationKeys.enter_phone_number: 'أدخل رقم هاتفك',
          LocalizationKeys.phone_confirmation: 'هيجيلك رسالة تأكيد على موبايلك',
          LocalizationKeys.phone_number: 'رقم الهاتف',
          LocalizationKeys.phone_number_hint: '01xxxxxxxxx',
          LocalizationKeys.phone_number_error: 'رقم الهاتف غير صحيح',
          LocalizationKeys.phone_number_error_empty: 'رقم الهاتف فاضي',
          LocalizationKeys.phone_number_error_length:
              'رقم الموبايل لازم يكون 11 رقم',
          LocalizationKeys.phone_number_error_format:
              'رقم الموبايل يجب أن يكون بالشكل 01xxxxxxxxx',
          LocalizationKeys.app_login: 'تسجيل الدخول بالموبايل',
          LocalizationKeys.app_logout: 'تسجيل الخروج',
          LocalizationKeys.app_logout_error: 'حدث خطأ في تسجيل الخروج',
          LocalizationKeys.login_google: 'سجل الدخول بحساب جوجل',
          LocalizationKeys.login_facebook: 'سجل الدخول بحساب فيسبوك',
          LocalizationKeys.or: 'أو',
          LocalizationKeys.login_error: 'حدث خطأ في تسجيل الدخول !',
          LocalizationKeys.network_error: 'حدث خطأ في الشبكة',
          LocalizationKeys.network_error_message:
              'يرجى التأكد من اتصالك بالشبكة وحاول مرة أخرى',
          LocalizationKeys.network_success: 'تم الاتصال بالشبكة',
          LocalizationKeys.network_success_message: 'لقد قمت بالاتصال بالشبكة',
          LocalizationKeys.facebook_login_error:
              'حدث خطأ في تسجيل الدخول بحساب فيسبوك',
          LocalizationKeys.filter_apply: 'تطبيق',
          LocalizationKeys.filter: 'تصفية',
          LocalizationKeys.filter_clear_all: 'مسح الكل',
          LocalizationKeys.choose_government: 'اختر المحافظة',
          LocalizationKeys.choose_area: 'اختر المنطقة',
          LocalizationKeys.choose_sex: 'اختر النوع',
          LocalizationKeys.choose_education: 'اختر المرحلة',
          LocalizationKeys.choose_class: 'اختر الصف',
          LocalizationKeys.male: 'ذكر',
          LocalizationKeys.female: 'أنثى',
          LocalizationKeys.education_secondary: 'المرحلة الثانوية',
          LocalizationKeys.education_prep: 'المرحلة الاعداداية',

          LocalizationKeys.secondary: 'ثانوى',
          LocalizationKeys.prep: 'اعدادي',
          // LocalizationKeys.education: 'المرحلة الدراسية',
          LocalizationKeys.class_level: 'الصف الدراسي',
          LocalizationKeys.secondary_class_level_one: 'الصف الأول الثانوى',
          LocalizationKeys.secondary_class_level_two: 'الصف الثانى الثانوى',
          LocalizationKeys.secondary_class_level_three: 'الصف الثالث الثانوى',
          LocalizationKeys.prep_class_level_one: 'الصف الأول الاعدادى',
          LocalizationKeys.prep_class_level_two: 'الصف الثانى الاعدادى',
          LocalizationKeys.prep_class_level_three: 'الصف الثالث الاعدادى',
          LocalizationKeys.home: 'الرئيسية',
          LocalizationKeys.follows: 'اتابعهم',
          LocalizationKeys.follows2: 'اتابعه',
          LocalizationKeys.followers: 'المتابعين',
          LocalizationKeys.notifications: 'الإشعارات',
          LocalizationKeys.news: 'الأخبار',
          LocalizationKeys.news_teachers: 'أخبار المدرسين',
          LocalizationKeys.profile: 'الحساب',
          LocalizationKeys.personal_info: 'المعلومات الشخصية',
          LocalizationKeys.choose_material: 'اختر المادة',
          //material
          LocalizationKeys.arabic: 'العربية',
          LocalizationKeys.math: 'الرياضيات',
          LocalizationKeys.science: 'العلوم',
          LocalizationKeys.social: 'الدراسات الاجتماعية',
          LocalizationKeys.biology: 'البيولوجية',
          LocalizationKeys.chemistry: 'الكيمياء',
          LocalizationKeys.physics: 'الفيزياء',
          LocalizationKeys.geography: 'الجغرافيا',
          LocalizationKeys.history: 'التاريخ',
          LocalizationKeys.french: 'الفرنسية',
          LocalizationKeys.english: 'الإنجليزية',
          LocalizationKeys.german: 'الألمانية',
          LocalizationKeys.spanish: 'الإسبانية',
          LocalizationKeys.price_avg: 'متوسط سعر الحصة',
          LocalizationKeys.save: 'حفظ',
          LocalizationKeys.rating: 'التقييم',
          LocalizationKeys.rate_teacher: 'قم بتقييم المدرس',
          LocalizationKeys.add_review: 'قيم الأن',
          LocalizationKeys.review_added: 'تمت إضافة تقييمك',
          LocalizationKeys.reviews: 'التقييمات',
          LocalizationKeys.no_reviews: 'لا يوجد تقييمات حتى الآن',
          LocalizationKeys.noFollows: 'لا يوجد متابعين حتى الآن',
          LocalizationKeys.review_text_hint: 'اكتب تقييمك (اختياري)',
          LocalizationKeys.review_already_rated_teacher:
              'لقد قمت بالفعل بتقييم هذا المدرس من قبل',
          LocalizationKeys.lectures: 'الحصص',
          LocalizationKeys.app_student: 'تطبيق الطالب',
          LocalizationKeys.enter_sms_code: 'ادخل الكود المرسل اليك',
          LocalizationKeys.enter_six_digits_code:
              'ادخل الكود المكون من 6 ارقام',
          LocalizationKeys.resend_sms_code: 'إعادة إرسال الكود',
          LocalizationKeys.sms_code_not_sent_question: 'لم يتم إرسال الكود؟',
          LocalizationKeys.app_cancel: 'إلغاء',
          LocalizationKeys.app_ok: 'موافق',
          LocalizationKeys.app_delete: 'حذف',
          LocalizationKeys.logout_confirmation: 'هل أنت متأكد من تسجيل الخروج؟',
          LocalizationKeys.confirm: 'تأكيد',
          LocalizationKeys.price_average: 'متوسط السعر',
          LocalizationKeys.settings: 'الإعدادات',
          LocalizationKeys.bookings: 'الحجوزات',
          LocalizationKeys.last_bookings: 'الحجوزات السابقة',
          LocalizationKeys.booking: 'حجز',
          LocalizationKeys.confirm_booking: 'تأكيد الحجز',
          LocalizationKeys.cancel_booking: 'الغاء الحجز',
          LocalizationKeys.delete_follow: 'الغاء المتابعة',
          LocalizationKeys.lecture_booked:
              'تم حجز الحصة بنجاح! يمكنك الاطلاع على الحجز على الصفحة الخاصة بالحجز',

          LocalizationKeys.profile_updated_error:
              'حدث خطأ أثناء تحديث الملف الشخصي',
          LocalizationKeys.profile_updated_successfully:
              'تم تحديث الملف الشخصي بنجاح',
          LocalizationKeys.profile_image_updated_successfully:
              'تم تحديث صورة الملف الشخصي بنجاح',
          LocalizationKeys.profile_image_updated_error:
              'حدث خطأ أثناء تحديث صورة الملف الشخصي',
          LocalizationKeys.gallery: 'اختر من مكتبة الصور',
          LocalizationKeys.camera: 'اختر من الكاميرا',
          LocalizationKeys.email_error_empty: 'البريد الإلكتروني فاضى',
          LocalizationKeys.email_error_format: 'البريد الإلكتروني مش صح',
          LocalizationKeys.name_error_empty: 'الاسم فاضى',
          LocalizationKeys.full_name: 'الاسم الكامل',
          LocalizationKeys.app_error_update_data: 'خطأ في تحديث البيانات',
          LocalizationKeys.choose_government_error: 'يجب اختيار المحافظة',
          LocalizationKeys.choose_area_error: 'يجب اختيار المنطقة',
          LocalizationKeys.following: 'متابعة',
          LocalizationKeys.follow_delete_question:
              'هل أنت متأكد من الغاء المتابعة؟',
          LocalizationKeys.follow_teacher_no_posts:
              'لازم تتابع المدرس عشان تقدر تشوف الاخبار اللى منزلها',
          LocalizationKeys.booking_delete_question:
              'هل أنت متأكد من الغاء الحجز؟',
          LocalizationKeys.app_yes: 'نعم',
          LocalizationKeys.app_no: 'لا',
          LocalizationKeys.notifications_not_found: 'لا يوجد إشعارات',
          LocalizationKeys.loading: 'جاري التحميل ...',
          LocalizationKeys.lecture_already_booked: 'تم حجز الحصة بالفعل',
          LocalizationKeys.lectures_not_found: 'لا يوجد حصص حتى الآن',
          LocalizationKeys.teachers_not_found: 'لا يوجد مدرسين',
          LocalizationKeys.bookings_not_found: 'لا يوجد حجوزات حتى الآن',
          LocalizationKeys.price_from: 'السعر من',
          LocalizationKeys.price_to: 'السعر إلى',
          LocalizationKeys.noFollows: 'لم تتابع أي مدرس حتى الآن',
          LocalizationKeys.government_cairo: 'القاهرة',
          LocalizationKeys.government_giza: 'الجيزة',
          LocalizationKeys.area_saft: 'صفت اللبن',
          LocalizationKeys.area_dokki: 'الدقي',

          //cairo area
          LocalizationKeys.cairo_nasrCity: 'مدينة نصر',
          LocalizationKeys.cairo_masr_gedida: 'مصر الجديدة',
          LocalizationKeys.cairo_maady: 'المعادي',
          LocalizationKeys.cairo_sayeda_zynab: 'السيدة زينب',
          LocalizationKeys.cairo_al_mokattam: 'المقطم',
          LocalizationKeys.cairo_ain_shams: 'عين شمس',
          LocalizationKeys.cairo_masra: 'المعصرة',
          LocalizationKeys.cairo_al_salam: 'السلام',
          LocalizationKeys.cairo_al_marg: 'المرج',
          LocalizationKeys.cairo_7lwan: 'حلوان',
          LocalizationKeys.cairo_mataria: 'المطرية',
          LocalizationKeys.cairo_nozha: 'النزهة',
          LocalizationKeys.cairo_west_balad: 'وسط البلد',
          LocalizationKeys.cairo_azbkya: 'الأزبكية',
          LocalizationKeys.cairo_moskey: 'الموسكى',
          LocalizationKeys.cairo_waily: 'الوايلي',
          LocalizationKeys.cairo_bab_sh3rya: 'باب الشعرية',
          LocalizationKeys.cairo_bola2: 'بولاق',
          LocalizationKeys.cairo_eltben: 'التبين',
          LocalizationKeys.cairo_3abden: 'عابدين',
          LocalizationKeys.cairo_3arb: 'غرب',
          LocalizationKeys.cairo_monsh2t_nasr: 'منشأة ناصر',
          LocalizationKeys.cairo_mayo_15: '15 مايو',
          LocalizationKeys.cairo_al_basaten: 'البساتين',
          LocalizationKeys.cairo_al_5alefa: 'الخليفة',
          LocalizationKeys.cairo_dar_salam: 'دار السلام',
          LocalizationKeys.cairo_torra: 'طرة',
          LocalizationKeys.cairo_misr_2adema: 'مصر القديمة',
          LocalizationKeys.cairo_amiria: 'الأميرية',
          LocalizationKeys.cairo_zawya: 'الزاوية',
          LocalizationKeys.cairo_zyton: 'الزيتون',
          LocalizationKeys.cairo_sahel: 'الساحل',
          LocalizationKeys.cairo_sharabya: 'الشرابية',
          LocalizationKeys.cairo_7dayk_2obba: 'حدائق القبة',
          LocalizationKeys.cairo_rod_elfarag: 'روض الفرج',
          LocalizationKeys.cairo_shobra: 'شبرا',
          LocalizationKeys.cairo_7dayk_maady: 'حدائق المعادي',
          LocalizationKeys.cairo_tagamo3: 'التجمع',
          LocalizationKeys.cairo_zamalek: 'الزمالك',

          //giza area
          LocalizationKeys.giza_dokki_or_mohandessen: 'الدقي أو المهندسين',
          LocalizationKeys.giza_agoza: 'العجوزة',
          LocalizationKeys.giza_kitkat: 'الكيت كات',
          LocalizationKeys.giza_embaba: 'إمبابة',
          LocalizationKeys.giza_warrak: 'الوراق',
          LocalizationKeys.giza_7dayk_ahram: 'حدائق الأهرام',
          LocalizationKeys.giza_3yad: 'العياط',
          LocalizationKeys.giza_kedasa: 'كرداسة',
          LocalizationKeys.giza_awsym: 'أوسيم',
          LocalizationKeys.giza_mansorya: 'المنصورية',
          LocalizationKeys.giza_nahya: 'ناهية',
          LocalizationKeys.giza_saft: 'صفت اللبن',
          LocalizationKeys.giza_monsh2t_elbakary: 'منشأة البكاري',
          LocalizationKeys.giza_she5_zayed: 'الشيخ زايد',
          LocalizationKeys.giza_bolak_dakror: 'بولاق الدكرور',
          LocalizationKeys.giza_midan_lebnan: 'ميدان لبنان',
          LocalizationKeys.giza_met_3o2ba: 'ميت عقبة',
          LocalizationKeys.giza_medan_gam3a: 'مدان الجامعة',
          LocalizationKeys.giza_midan_giza: 'ميدان الجيزة',
          LocalizationKeys.giza_haram: 'الهرم',
          LocalizationKeys.giza_faisel: 'فيصل',
          LocalizationKeys.giza_omranya: 'العمرانية',
          LocalizationKeys.giza_om_masryyn: 'أم المصريين',
          LocalizationKeys.giza_m2mon: 'المأمون',
          LocalizationKeys.giza_6_october: '6 أكتوبر',
          LocalizationKeys.giza_sa2ya_mky: 'ساقية مكي',
          LocalizationKeys.giza_monyb: 'المنيب',
          LocalizationKeys.giza_tersa: 'ترسا',
          LocalizationKeys.giza_hawamdya: 'الحوامدية',
          LocalizationKeys.giza_3zyzya: 'العزيزية',
          LocalizationKeys.giza_s2ara: 'سقارة',
          LocalizationKeys.giza_bdrshen: 'البدرشين',
        },
      };
}
