import 'package:get/get.dart';

import 'localization_keys.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          LocalizationKeys.enter_phone_number: 'Enter your phone number',
          LocalizationKeys.phone_confirmation:
              'you will receive a confirmation code on your phone',
          LocalizationKeys.phone_number: 'Phone number',
          LocalizationKeys.phone_number_hint: '01xxxxxxxxx',
          LocalizationKeys.phone_number_error: 'Phone number is wrong',
          LocalizationKeys.phone_number_error_empty: 'Phone number is empty',
          LocalizationKeys.phone_number_error_length:
              'Phone number must be at least 11 digits',
          LocalizationKeys.phone_number_error_format:
              'Phone number must be in the format 01xxxxxxxxx',
          LocalizationKeys.app_login: 'Login with phone number',
          LocalizationKeys.app_logout: 'Logout',
          LocalizationKeys.login_google: 'Login with Google',
          LocalizationKeys.login_facebook: 'Login with Facebook',
          LocalizationKeys.or: 'OR',
          LocalizationKeys.filter_apply: 'Apply',
          LocalizationKeys.filter_clear_all: 'Clear all',
          LocalizationKeys.login_error: 'Login error happened !',
          LocalizationKeys.network_error: 'Network error happened !',
          LocalizationKeys.network_error_message:
              'Please check your internet connection and try again',
          LocalizationKeys.network_success: 'Network success !',
          LocalizationKeys.network_success_message:
              'You are connected to the internet',
          LocalizationKeys.facebook_login_error:
              'Login with Facebook error happened !',
          LocalizationKeys.government_cairo: 'Cairo',
          LocalizationKeys.area_saft: 'Saft',
          LocalizationKeys.area_dokki: 'Dokki',
          LocalizationKeys.choose_government: 'Choose government',
          LocalizationKeys.choose_area: 'Choose area',
          LocalizationKeys.choose_sex: 'Choose type',
          LocalizationKeys.choose_education: 'Choose Education',
          LocalizationKeys.choose_class: 'Choose Class',
          LocalizationKeys.choose_material: 'Choose Material',
          LocalizationKeys.male: 'Male',
          LocalizationKeys.female: 'Female',
          LocalizationKeys.education_secondary: 'Secondary',
          LocalizationKeys.education_prep: 'Secondary',
          LocalizationKeys.class_level: 'class level',
          LocalizationKeys.class_level_one: 'One',
          LocalizationKeys.class_level_two: 'Two',
          LocalizationKeys.class_level_three: 'Three',
          LocalizationKeys.home: 'Home',
          LocalizationKeys.follows: 'Follows',
          LocalizationKeys.followers: 'Followers',
          LocalizationKeys.notifications: 'Notifications',
          LocalizationKeys.profile: 'Profile',
          LocalizationKeys.personal_info: 'Personal Info',
          LocalizationKeys.price_avg: 'Avg Price',
          //material
          LocalizationKeys.arabic: 'Arabic',
          LocalizationKeys.english: 'English',
          LocalizationKeys.math: 'Math',
          LocalizationKeys.science: 'Science',
          LocalizationKeys.french: 'French',
          LocalizationKeys.history: 'History',
          LocalizationKeys.geography: 'Geography',
          LocalizationKeys.biology: 'Biology',
          LocalizationKeys.chemistry: 'Chemistry',
          LocalizationKeys.physics: 'Physics',
          LocalizationKeys.german: 'German',
          LocalizationKeys.spanish: 'Spanish',
          LocalizationKeys.social: 'Social',
          LocalizationKeys.save: 'save',
          LocalizationKeys.rating: 'Rating',
          LocalizationKeys.reviews: 'Reviews',
          LocalizationKeys.no_reviews: 'No Reviews Yet',
          LocalizationKeys.lectures: 'Lectures',
          LocalizationKeys.app_student: 'Student App',
          LocalizationKeys.sms_code: 'SMS Code',
          LocalizationKeys.enter_six_digits_code: 'Enter 6 digits code',
          LocalizationKeys.enter_sms_code: 'Enter the code sent to you by SMS',
          LocalizationKeys.resend_sms_code: 'Resend SMS Code',
          LocalizationKeys.sms_code_not_sent_question: 'SMS Code not sent ?',
          LocalizationKeys.app_cancel: 'Cancel',
          LocalizationKeys.app_ok: 'Ok',
          LocalizationKeys.logout_confirmation:
              'Are you sure you want to logout ?',
          LocalizationKeys.confirm: 'Confirm',
        },
        'ar_EG': {
          LocalizationKeys.enter_phone_number: 'أدخل رقم هاتفك',
          LocalizationKeys.phone_confirmation: 'هيجيلك رسالة تأكيد على موبايلك',
          LocalizationKeys.phone_number: 'رقم الهاتف',
          LocalizationKeys.phone_number_hint: '01xxxxxxxxx',
          LocalizationKeys.phone_number_error: 'رقم الهاتف غير صحيح',
          LocalizationKeys.phone_number_error_empty: 'رقم الهاتف فاضي',
          LocalizationKeys.phone_number_error_length:
              'رقم الموبايل لازم يكون 11 رقم',
          LocalizationKeys.phone_number_error_format:
              'رقم الموبايل يجب أن يكون بالشكل 01xxxxxxxxx',
          LocalizationKeys.app_login: 'تسجيل الدخول بالموبايل',
          LocalizationKeys.app_logout: 'تسجيل الخروج',
          LocalizationKeys.login_google: 'سجل الدخول بحساب جوجل',
          LocalizationKeys.login_facebook: 'سجل الدخول بحساب فيسبوك',
          LocalizationKeys.or: 'أو',
          LocalizationKeys.login_error: 'حدث خطأ في تسجيل الدخول !',
          LocalizationKeys.network_error: 'حدث خطأ في الشبكة',
          LocalizationKeys.network_error_message:
              'يرجى التأكد من اتصالك بالشبكة وحاول مرة أخرى',
          LocalizationKeys.network_success: 'تم الاتصال بالشبكة',
          LocalizationKeys.network_success_message: 'لقد قمت بالاتصال بالشبكة',
          LocalizationKeys.facebook_login_error:
              'حدث خطأ في تسجيل الدخول بحساب فيسبوك',
          LocalizationKeys.filter_apply: 'تطبيق',
          LocalizationKeys.filter_clear_all: 'مسح الكل',
          LocalizationKeys.government_cairo: 'القاهرة',
          LocalizationKeys.government_giza: 'الجيزة',
          LocalizationKeys.area_saft: 'صفت اللبن',
          LocalizationKeys.area_dokki: 'الدقي',
          LocalizationKeys.choose_government: 'اختر المحافظة',
          LocalizationKeys.choose_area: 'اختر المنطقة',
          LocalizationKeys.choose_sex: 'اختر النوع',
          LocalizationKeys.choose_education: 'اختر المرحلة',
          LocalizationKeys.choose_class: 'اختر الصف',
          LocalizationKeys.male: 'ذكر',
          LocalizationKeys.female: 'أنثى',
          LocalizationKeys.education_secondary: 'المرحلة الثانوية',
          LocalizationKeys.education_prep: 'المرحلة الاعداداية',
          // LocalizationKeys.education: 'المرحلة الدراسية',
          LocalizationKeys.class_level: 'الصف الدراسي',
          LocalizationKeys.class_level_one: 'الصف الدراسي الأول',
          LocalizationKeys.class_level_two: 'الصف الدراسي الثاني',
          LocalizationKeys.class_level_three: 'الصف الدراسي الثالث',
          LocalizationKeys.home: 'الرئيسية',
          LocalizationKeys.follows: 'اتابعهم',
          LocalizationKeys.followers: 'المتابعين',
          LocalizationKeys.notifications: 'الإشعارات',
          LocalizationKeys.profile: 'الحساب',
          LocalizationKeys.personal_info: 'المعلومات الشخصية',
          LocalizationKeys.choose_material: 'اختر المادة',
          //material
          LocalizationKeys.arabic: 'العربية',
          LocalizationKeys.math: 'الرياضيات',
          LocalizationKeys.science: 'العلوم',
          LocalizationKeys.social: 'الدراسات الاجتماعية',
          LocalizationKeys.biology: 'البيولوجية',
          LocalizationKeys.chemistry: 'الكيمياء',
          LocalizationKeys.physics: 'الفيزياء',
          LocalizationKeys.geography: 'الجغرافيا',
          LocalizationKeys.history: 'التاريخ',
          LocalizationKeys.french: 'الفرنسية',
          LocalizationKeys.english: 'الإنجليزية',
          LocalizationKeys.german: 'الألمانية',
          LocalizationKeys.spanish: 'الإسبانية',
          LocalizationKeys.price_avg: 'متوسط سعر الحصة',
          LocalizationKeys.save: 'حفظ',
          LocalizationKeys.rating: 'التقييم',
          LocalizationKeys.reviews: 'التقييمات',
          LocalizationKeys.no_reviews: 'لا يوجد تقييمات حتى الآن',
          LocalizationKeys.lectures: 'الحصص',
          LocalizationKeys.app_student: 'تطبيق الطالب',
          LocalizationKeys.enter_sms_code: 'ادخل الكود المرسل اليك',
          LocalizationKeys.enter_six_digits_code:
              'ادخل الكود المكون من 6 ارقام',
          LocalizationKeys.resend_sms_code: 'إعادة إرسال الكود',
          LocalizationKeys.sms_code_not_sent_question: 'لم يتم إرسال الكود؟',
          LocalizationKeys.app_cancel: 'إلغاء',
          LocalizationKeys.app_ok: 'موافق',
          LocalizationKeys.logout_confirmation: 'هل أنت متأكد من تسجيل الخروج؟',
          LocalizationKeys.confirm: 'تأكيد',
        },
      };
}
