// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTvgz05wIK0UJASub7GOLCvVb7lgyfwyU',
    appId: '1:433329454491:android:15bfcaa8b7b551f921753e',
    messagingSenderId: '433329454491',
    projectId: 'droos-21f2c',
    storageBucket: 'droos-21f2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWw_y3SMzTmY5UDBWxG910ZA2urJvGQuI',
    appId: '1:433329454491:ios:1c5f839f686785f221753e',
    messagingSenderId: '433329454491',
    projectId: 'droos-21f2c',
    storageBucket: 'droos-21f2c.appspot.com',
    androidClientId: '433329454491-639t74o4tet44nkk693p65lvhcjk9det.apps.googleusercontent.com',
    iosClientId: '433329454491-fvl1ufvbgrt7msvho20hvugg6ol9ulbq.apps.googleusercontent.com',
    iosBundleId: 'com.drosak.drosak',
  );
}
