// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3CFtUi_Qi86Fee0VJYcTQ3H4_kJA98uw',
    appId: '1:302813141932:android:072d13f909bf9aa3a2b809',
    messagingSenderId: '302813141932',
    projectId: 'drosak-prod',
    storageBucket: 'drosak-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmhVrqUUIHiNnYs5MX6bscT2gDqxz-EfQ',
    appId: '1:302813141932:ios:fd2749c807f8c29ea2b809',
    messagingSenderId: '302813141932',
    projectId: 'drosak-prod',
    storageBucket: 'drosak-prod.appspot.com',
    androidClientId: '302813141932-8llld1jcsho04k9s5qnf159ev6da7sme.apps.googleusercontent.com',
    iosClientId: '302813141932-c8idfpe19rsg5nhvp248vvhi72g4ilo1.apps.googleusercontent.com',
    iosBundleId: 'com.drosak.drosak.prod',
  );
}
