import 'package:drosak/utils/localization/localization_keys.dart';
import 'package:get/get.dart';

class Filters {
  static final List<String> governments = [
    LocalizationKeys.government_cairo.tr,
    LocalizationKeys.government_giza.tr
  ];

  static final List<String> areasCairo = [
    LocalizationKeys.cairo_nasrCity.tr,
    LocalizationKeys.cairo_masr_gedida.tr,
    LocalizationKeys.cairo_maady.tr,
    LocalizationKeys.cairo_sayeda_zynab.tr,
    LocalizationKeys.cairo_al_mokattam.tr,
    LocalizationKeys.cairo_ain_shams.tr,
    LocalizationKeys.cairo_masra.tr,
    LocalizationKeys.cairo_al_salam.tr,
    LocalizationKeys.cairo_al_marg.tr,
    LocalizationKeys.cairo_7lwan.tr,
    LocalizationKeys.cairo_mataria.tr,
    LocalizationKeys.cairo_nozha.tr,
    LocalizationKeys.cairo_west_balad.tr,
    LocalizationKeys.cairo_azbkya.tr,
    LocalizationKeys.cairo_moskey.tr,
    LocalizationKeys.cairo_waily.tr,
    LocalizationKeys.cairo_bab_sh3rya.tr,
    LocalizationKeys.cairo_bola2.tr,
    LocalizationKeys.cairo_eltben.tr,
    LocalizationKeys.cairo_3abden.tr,
    LocalizationKeys.cairo_3arb.tr,
    LocalizationKeys.cairo_monsh2t_nasr.tr,
    LocalizationKeys.cairo_mayo_15.tr,
    LocalizationKeys.cairo_al_basaten.tr,
    LocalizationKeys.cairo_al_5alefa.tr,
    LocalizationKeys.cairo_dar_salam.tr,
    LocalizationKeys.cairo_torra.tr,
    LocalizationKeys.cairo_misr_2adema.tr,
    LocalizationKeys.cairo_amiria.tr,
    LocalizationKeys.cairo_zawya.tr,
    LocalizationKeys.cairo_zyton.tr,
    LocalizationKeys.cairo_sahel.tr,
    LocalizationKeys.cairo_sharabya.tr,
    LocalizationKeys.cairo_7dayk_2obba.tr,
    LocalizationKeys.cairo_rod_elfarag.tr,
    LocalizationKeys.cairo_shobra.tr,
    LocalizationKeys.cairo_7dayk_maady.tr,
    LocalizationKeys.cairo_tagamo3.tr,
    LocalizationKeys.cairo_zamalek.tr,
    LocalizationKeys.cairo_obor.tr,
    LocalizationKeys.cairo_shrouk.tr,
  ];

  static final List<String> areasGiza = [
    LocalizationKeys.giza_dokki_or_mohandessen.tr,
    LocalizationKeys.giza_agoza.tr,
    LocalizationKeys.giza_kitkat.tr,
    LocalizationKeys.giza_embaba.tr,
    LocalizationKeys.giza_warrak.tr,
    LocalizationKeys.giza_7dayk_ahram.tr,
    LocalizationKeys.giza_3yad.tr,
    LocalizationKeys.giza_kedasa.tr,
    LocalizationKeys.giza_awsym.tr,
    LocalizationKeys.giza_mansorya.tr,
    LocalizationKeys.giza_nahya.tr,
    LocalizationKeys.giza_saft.tr,
    LocalizationKeys.giza_monsh2t_elbakary.tr,
    LocalizationKeys.giza_she5_zayed.tr,
    LocalizationKeys.giza_bolak_dakror.tr,
    LocalizationKeys.giza_midan_lebnan.tr,
    LocalizationKeys.giza_met_3o2ba.tr,
    LocalizationKeys.giza_medan_gam3a.tr,
    LocalizationKeys.giza_midan_giza.tr,
    LocalizationKeys.giza_haram.tr,
    LocalizationKeys.giza_faisel.tr,
    LocalizationKeys.giza_omranya.tr,
    LocalizationKeys.giza_om_masryyn.tr,
    LocalizationKeys.giza_m2mon.tr,
    LocalizationKeys.giza_6_october.tr,
    LocalizationKeys.giza_sa2ya_mky.tr,
    LocalizationKeys.giza_monyb.tr,
    LocalizationKeys.giza_tersa.tr,
    LocalizationKeys.giza_hawamdya.tr,
    LocalizationKeys.giza_3zyzya.tr,
    LocalizationKeys.giza_s2ara.tr,
    LocalizationKeys.giza_bdrshen.tr,
  ];
}
